# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 678473051153b080c94d529e9e4688426316b8d5d1c1f0019b623f059a5c3ffe02fc1336cd505e68ed049b1da36b4d81ee1db8bf9ab3890d7b8cf4dc0ea2a18d

test:
  secret_key_base: 9ba371a7d485b2f37bf6fb2d988c6a38e220ac7ca6ba329169a36b27df0ae90d3b414c35848b9d16baba7fb71ddc84544755fd9611716a24e03d6eb3d8fa6eb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
